defaults: 
  - _self_
  - physics:  phys_King_etal_2016_k_23_50 #phys_harris_lab_TL
  - mc: monte_carlo_crib
  - temp: temp_King_etal_2016_ii #temp_constant_T
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: disabled

setup:
  physics_name: Example
  project: "${mc.name}_${mc.exp_typ}_${setup.physics_name}"
  seed: 1

hydra:
  run:
    dir: "run/${setup.project}_${now:%Y%m%d-%H%M%S}"
  sweep: 
    dir: "run/${setup.project}_${now:%Y%m%d-%H%M%S}"
    subdir: "trial_${hydra.job.num}" 
  output_subdir: ".config"
  job:
    chdir : true 