defaults: 
  - _self_
  - physics:  phys_harris_lab_TL # phys_King_etal_2016_k_23 #
  - temp: temp_linear #temp_constant_T
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: disabled

setup:
  project: "Example"
  seed: 1
  t_pcnt    : 1      # Ratio of filled electrons traps
  h_pcnt    : 1     # Ratio of recombination holes that are unfilled
  reps      : 10     # Number of Monte Carlo simulations to repeat
  mc        : True   # Run monte Carlo simulations
  ac        : True  # Run analytic model 
  TC        : True  # Run thermo chronology


hydra:
  run:
    dir: "run/${setup.project}_${now:%Y%m%d-%H%M%S}"
  sweep: 
    dir: "run/${setup.project}_${now:%Y%m%d-%H%M%S}"
    subdir: "trial_${hydra.job.num}" 
  output_subdir: ".config"
  job:
    chdir : true 