setup:
  physics_name: Example
  project: ${mc.name}_${mc.exp_typ}_${setup.physics_name}
  seed: 1
physics:
  uc_h: 1.0e-10
  uc_w: 1.0e-10
  uc_l: 1.0e-10
  dimension: null
  E_loc: 1.4
  b: 1000000000000.0
  alpha: 9000000000.0
  alpha_GS: 100000000.0
  E_cb: null
  s: 10000000000000.0
  rho: null
  urho: 0.0003
  D0: null
  D_dot: null
  Dd_unit: Ka
  phys_type: null
mc:
  name: mc
  exp_typ: TL
  max_dt: 0.5
  t_pcnt: 1
  h_pcnt: 1
  reps: 10
  mc: true
  ac: false
temp:
  unit: s
  celsius: true
  kind: linear
  T0: 0
  duration: 160
  times:
  - 0.18
  - 0.275
  - 0.384
  - 0.467
  dT_step:
  - 20
  - 20
  - 20
  - 20
  dT:
  - -5
  T_inf: 0
  k: 10
