hydra:
  run:
    dir: run/${setup.project}_${now:%Y%m%d-%H%M%S}
  sweep:
    dir: run/${setup.project}_${now:%Y%m%d-%H%M%S}
    subdir: trial_${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    root:
      level: ERROR
    disable_existing_loggers: true
  job_logging:
    version: 1
    disable_existing_loggers: false
    formatters:
      std:
        format: '%(asctime)s | %(levelname)s | %(name)s | %(message)s'
    handlers:
      split:
        class: src.errors.ErrorOutputHandler
        formatter: std
        out_file: output.log
        err_file: error.log
        error_level: 40
        install_hooks: true
        logger_name: lumphys
        include_asyncio: true
        uncaught_level: 40
        duplicate_errors_to_out: false
    root:
      level: INFO
      handlers:
      - split
  env: {}
  mode: RUN
  searchpath: []
  callbacks: {}
  output_subdir: .config
  overrides:
    hydra:
    - hydra.mode=RUN
    task: []
  job:
    name: main_function
    chdir: true
    override_dirname: ''
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: C:\Users\hanta\Code\MonteCarloLuminescence
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: c:\Users\hanta\Code\MonteCarloLuminescence\conf
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: C:\Users\hanta\Code\MonteCarloLuminescence\run\mc_TL_Example_20260123-162544
    choices:
      temp: temp_linear
      mc: monte_carlo_crib
      physics: phys_harris_lab_TL
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: custom
      hydra/hydra_logging: disabled
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
